/*
 * FinalProject.web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FinalProjectApiCli.Api;
using FinalProjectApiCli.Model;
using FinalProjectApiCli.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FinalProjectApiCli.Test.Model
{
    /// <summary>
    ///  Class for testing MyTask
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MyTaskTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MyTask
        //private MyTask instance;

        public MyTaskTests()
        {
            // TODO uncomment below to create an instance of MyTask
            //instance = new MyTask();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MyTask
        /// </summary>
        [Fact]
        public void MyTaskInstanceTest()
        {
            // TODO uncomment below to test "IsType" MyTask
            //Assert.IsType<MyTask>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Fact]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }

    }

}
